[package]
name    = "m6-html"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[[bin]]
name = "m6-html"

[dependencies]
m6-core   = { path = "../m6-core" }
anyhow    = "1"

[dev-dependencies]
m6-core       = { path = "../m6-core", features = ["testkit"] }
tempfile      = "3"
brotli  = "6"
flate2  = "1"
